name: Call Random QTS Query Every 53 Minutes

on:
  schedule:
    - cron: '*/53 * * * *'
  workflow_dispatch:

jobs:
  call-api-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase GET Function 'qtsquery'
        run: |
          curl -f -L -X GET 'https://yxevuqaxdqrwowthcwkz.supabase.co/functions/v1/qtsquery' \
            -H "Authorization: Bearer ${{ secrets.ANON_KEY_NEW }}"
